version: '3.8'

services:
  pc-build-ai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - ./.env:/app/.env:ro
      - ./data:/app/data
      - ./configs:/app/configs
      - ./memory:/app/memory
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    command: python src/app.py
    networks:
      - pc-build-network

networks:
  pc-build-network:
    driver: bridge
