version: "3.9"
services:
  model_gpt35:
    build: .
    env_file: .env
    environment:
      - MODEL_NAME=gpt-3.5-turbo
    ports:
      - "8001:8000"

  model_gpt4o:
    build: .
    env_file: .env
    environment:
      - MODEL_NAME=gpt-4o
    ports:
      - "8002:8000"

  model_gpt4o_mini:
    build: .
    env_file: .env
    environment:
      - MODEL_NAME=gpt-4o-mini
    ports:
      - "8003:8000"

  # Сетевой прокси/балансировщик (опционально)
  # traefik:
  #   image: traefik:v2.11
  #   command:
  #     - "--providers.docker=true"
  #     - "--providers.docker.exposedbydefault=false"
  #     - "--entrypoints.web.address=:80"
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"
