@echo off
python -m isort src/app.py
python -m isort src/model_evaluator.py
python -m isort src/visualization.py
python -m isort src/run_complete_test.py
python -m isort src/db_validator.py
python -m isort src/token_counter.py
python -m isort src/generate_report.py
python -m isort src/chat_backend.py
python -m isort src/load_config.py
python -m isort src/tools/regard_parser.py
python -m isort src/tools/sql_agent_tools.py
python -m isort src/tools/bottle_neck.py
python -m isort src/tools/game_runner.py
python -m isort src/agent_shema/mult_agents_graph.py
python -m isort src/agent_shema/agent_runnables.py
python -m isort src/agent_shema/build_assistants.py
python -m isort src/agent_shema/build_agent_state.py
python -m isort src/agent_shema/build_system_prompts.py
python -m isort src/agent_shema/complete_or_escalate.py
python -m isort src/utils/ui_settings.py
python -m isort src/utils/utilities.py
python -m isort src/utils/app_utils.py
